defaults:
  - default
  - /model/architecture@denoiser_network_cfg: u_net_S
  - _self_

_target_: models.ConsistencyCT
_recursive_: false

sigma_data: 0.5
train_num_steps: 3
sigma_min: 0.002
sigma_max: 80
rho: 7
